const SET_USERS = 'SET_USERS';
const SET_USERS_LOADING = 'SET_USER_LOADING';
const REMOVE_USERS = 'REMOVE_USERS';
const SET_THEME = 'SET_THEME';

const SET_TODOS = 'SET_TODOS';
const SET_POSTS = 'SET_POSTS';

const SET_QUOTES ='SET_QUOTES';

export {
    SET_USERS,
    SET_USERS_LOADING,
    REMOVE_USERS,
    SET_THEME,
    SET_TODOS,
    SET_POSTS,
    SET_QUOTES
};