const SET_USERS = 'SET_USERS';
const SET_USERS_LOADING = 'SET_USER_LOADING';
const REMOVE_USERS = 'REMOVE_USERS';
const SET_THEME = 'SET_THEME';

const SET_TODOS = 'SET_TODOS';

export {
    SET_THEME,
    SET_TODOS,
    SET_USERS,
    SET_USERS_LOADING,
    REMOVE_USERS
};